package com.droidlib.kompose.utils

val TEXTSTYLE_NORMAL = 0
val TEXTSTYLE_BOLD = 1

val GRAVITY_CENTER = 17
val GRAVITY_LEFT = 3
val GRAVITY_LEFT_CENTERVERTICAL = 19
val GRAVITY_RIGHT = 5
val GRAVITY_RIGHT_CENTERVERTICAL = 21
val GRAVITY_TOP = 48
val GRAVITY_TOP_CENTERHORIZONTAL = 1
val GRAVITY_BOTTOM = 80
val GRAVITY_BOTTOM_CENTERHORIZONTAL = 81

val INPUT_TEXT = 1
val INPUT_NUMBER = 2
val INPUT_PHONE = 3
val INPUT_DATETIME = 4
val INPUT_NUMBER_DECIMAL = 8192
val INPUT_NUMBER_PASSWORD = 16
val INPUT_EMAIL = 32
val INPUT_TEXT_PASSWORD = 128
val INPUT_PERSONNAME = 96
val INPUT_DATE = 16
val INPUT_TIME = 32
